# Generated by Django 2.1.7 on 2019-06-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storm', '0003_auto_20190610_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='/static/images/article/default.jpg', max_length=255, verbose_name='图片地址'),
        ),
    ]
